// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cspqmlubrgxfpbqsahzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzcHFtbHVicmd4ZnBicXNhaHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NDkyODEsImV4cCI6MjA1NzUyNTI4MX0.CxdYC5IK3JDl6QmCWRDsWjbcagsn5W_wfnxc_E6t8ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);